[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maya-content-factory"
version = "0.1.0"
dependencies = [
    "alembic",
    "sqlalchemy",
    "psycopg2-binary",
    "beautifulsoup4",
    "httpx",
    "google-genai",
    "pillow",
]
